== Gründungsprotokoll

des Vereins

"Karate Bennwil"

abgehalten am 3. Februar 2019, um 20:00 Uhr in den Räumlichkeiten von Jonas Bieri Lüthy, In der Gasse 1, 4431 Bennwil.

=== 0. Traktandenliste

. Begrüssung und Feststellung der Beschlussfähigkeit 
. Genehmigung der Traktandenliste
. Wahl des Tagungspräsidenten
. Wahl der Protokollführerin
. Grund für die Errichtung des Vereins
. Genehmigung der Statuten des Vereins
. Wahl der Verwaltung
. Verzicht auf Revisionsstelle
. Allgemeine Umfrage

=== 1. Begrüssung und Feststellung der Beschlussfähigkeit

Jonas Bieri Lüthy begrüsst als Einladende die Anwesenden und stellt fest, dass für die Gründung des Vereins "Karate Bennwil" folgende Personen anwesend sind:

* Jonas Bieri Lüthy, wohnhaft in Bennwil, als Gründungsmitglied
* Rahel Lüthy, wohnhaft in Bennwil, als Gründungsmitglied

Demnach ist die gemäss Art. 60 ff. ZGB zur Gründung eines Vereins erforderliche
Zahl von mindestens zwei Gründungsmitgliedern vorliegend erfüllt und die
Gründungsversammlung beschlussfähig.

=== 2. Genehmigung der Traktandenliste

Auf Antrag von Jonas Bieri Lüthy wird die Traktandenliste einstimmig genehmigt.

=== 3. Wahl des Tagungspräsidenten

Jonas Bieri Lüthy erklärt sich bereit, als Tagungspräsident zu fungieren. Der
Vorschlag wird von der Gründungsversammlung einstimmig gutgeheissen und Jonas
Bieri Lüthy übernimmt den Vorsitz der Gründungsversammlung.

=== 4. Wahl der Protokollführerin

Auf Antrag von Jonas Bieri Lüthy wird Rahel Lüthy als Protokollführerin der
Gründungsversammlung bestimmt.

=== 5. Grund für die Errichtung des Vereins

Der Verein "Karate Bennwil" unterstützt und ermöglicht das Training in Karate 
und anderen Kampfkunstarten. 

Die Statuten gemäss Beilage werden einstimmig von der Gründungsversammlung
angenommen.

Jonas Bieri erklärt die Gründung des Vereins "Karate Bennwil" als vollzogen.

=== 8. Wahl des Vorstands

Die Gründungsversammlung wählt für die Dauer von einem Jahr bis zur ordentlichen
Hauptversammlung im Jahre 2020 folgende Mitglieder des Vorstands:

* Jonas Bieri Lüthy als Präsidenten, Aktuar und Kassierer; mit Kollektivunterschrift
zu zweien
* Rahel Lüthy als Vizepräsidentin, mit Kollektivunterschrift zu zweien

Die Gewählten nehmen die Wahl an.

=== 9. Verzicht auf Revisionsstelle

Der Tagespräsident stellt fest, dass der Verein nicht zur ordentlichen
Revision gemäss Art. 69b Abs. 1 ZGB verpflichtet ist. Nachdem der Verein
weniger als 10 Vollzeitstellen im Jahresdurchschnitt haben wird, beschliesst
die Gründungsversammlung einstimmig, auf eine Revisionsstelle gemäss Art. 69b
Abs. 3 ZGB i.V.m. Art. 727a Abs. 2 OR zu verzichten.

=== 10. Allgemeine Umfrage

Der Vorsitzende dankt zum Schluss allen Anwesenden für die tatkräftige
Unterstützung. Die allgemeine Umfrage wird nicht weiter benutzt, und die
Vorsitzende schliesst die Versammlung um 20:30 Uhr.

Bennwil, 04.02.2019 

Rahel Lüthy (Protokollführerin):

Jonas Bieri Lüthy (Präsident):