== Vereinsstatuten

[.text-center]
Verein 'Karate Bennwil' +
mit Sitz in Bennwil

=== Name und Sitz
Unter dem Namen „Karate Bennwil“ besteht ein Verein im Sinne von Art. 60 ff.
ZGB mit Sitz in Bennwil. Er ist politisch und konfessionell neutral.

=== Ziel und Zweck
Der Verein ermöglicht und unterstützt das Training in Karate und anderen 
Kampfkunstarten. 

Er verfolgt keinen politischen oder kommerziellen Zweck. Die Organe
sind ehrenamtlich tätig.

=== Mittel 
Die Mittel des Vereins setzen sich aus Mitgleiderbeiträgen, Spenden und Zuwendungen zusammen. 

=== Mitglieder
Mitglieder sind natürliche und juristische Person, die ein Interesse am
Vereinszweck haben.

=== Erlöschen & Austritt 
Die Mitgliedschaft erlischt

* bei natürlichen Personen durch Austritt, Ausschluss oder Tod
* bei juristischen Personen durch Austritt, Ausschluss oder Auflösung

Der Vereinsaustritt ist jederzeit möglich.

=== Organe
Die Organe des Vereins sind:

* die Mitgliederversammlung
* der Vorstand

=== Kommunikation
Die Kommunikation des Vereins mit den Mitgliedern erfolgt postalisch und/oder
elektronisch. 

=== Mitgliederversammlung
Das oberste Organ des Vereins ist die Mitgliederversammlung. Eine ordentliche
Mitgliederversammlung findet jährlich im 1. Quartal statt.

Zur Mitgliederversammlung werden die Mitglieder 30 Tage im Voraus schriftlich
unter Angabe der Traktanden eingeladen. Elektronische Einladungen sind gültig.

Traktandierungsanträge zuhanden der Mitgliederversammlung sind bis spätestens
10 Tage schriftlich an den Vorstand zu richten.

Die Mitgliederversammlung hat die folgenden unentziehbaren Aufgaben:

*  Wahl der Präsidentin resp. des Präsidenten
*  Festsetzung und Änderung der Statuten
*  Abnahme der Jahresrechnung
*  Entlastung des Vorstandes
*  Beschluss über das Jahresbudget
*  Zweckänderung und Auflösung des Vereins

=== Vorstand
Der Vorstand besteht aus einer Präsidentin resp. einem Präsidenten und einer Vizepräsidentin resp. einem Vizepräsidenten.

Der Vorstand konstituiert sich selbst.

Die Mitglieder des Vorstandes werden für eine Amtsdauer von einem Jahr gewählt.

Der Vorstand ist grundsätzlich ehrenamtlich tätig, er hat Anrecht auf Vergütung
der effektiven Spesen. Er kann für die Erreichung der Vereinsziele Personen
gegen eine angemessene Entschädigung anstellen oder beauftragen.

=== Zeichnungsberechtigung
Der Vorstand regelt die Zeichnungsberechtigung zu zweien.

=== Haftung
Für die Schulden des Vereins haftet ausschliesslich das
Vereinsvermögen. Die persönliche Haftung und insbesondere eine
Nachschusspflicht der Mitglieder ist ausgeschlossen.

=== Auflösung
Der Vorstand kann jederzeit über die Auflösung des Vereins bestimmen.

Bei einer Auflösung fällt das Vereinsvermögen an eine Organisation, 
welche den gleichen oder einen ähnlichen Zweck verfolgt. Die
Verteilung des Vereinsvermögens unter den Mitgliedern ist ausgeschlossen. 

=== Inkrafttreten
Diese Statuten wurden an der Gründungsversammlung vom 3. Februar 2019 angenommen und
sind mit diesem Datum in Kraft getreten.

Bennwil, 3. Februar 2019 

Rahel Lüthy (Protokollführerin):

Jonas Bieri Lüthy (Präsident):